config/routes.rb
Rails.application.routes.draw do
  # root :to => 'home#index'
  get '/' => 'home#index'
  get '/log-in' => "sessions#new"
  post '/log-in' => "sessions#create"
  get '/log-out' => "sessions#destroy", as: :log_out

  resources :users
  resources :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, uniqueness: true
  validates :password, length: { in: 6..20 }
  before_save :encrypt_password
  validates :email, :presence => true
  has_many :photos

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new

  end

  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      flash[:notice] = "Photo added successfully!"
      redirect_to photo_path
    else
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(current_user)
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created successfully!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem, yo."
      redirect_to :back
    end
  end

  def show

  end

  def update

  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<span class="success"><%= flash[:notice] %></span>
<span class="fail"><%= flash[:alert] %></span>

<h1>Welcome to my Website</h1>
<% if current_user %>
  <h3>You are logged in as: <span class="user"><%= current_user.email %></span></h3>
<% end %>

<% if @users.any? %>
  <% @users.each do |user| %>
    <ul>
      <li><%= user.email %></li>
    </ul>
  <% end %>
<% end %>

<%= link_to "Add New User", new_user_path, :class => "btn btn-success" %>

<%= link_to "Log In", log_in_path, :class => "btn btn-primary" %>

<%= link_to "Log Out", log_out_path, :class => "btn btn-warning" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoSharing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="app/assets/stylesheets/bootstrap-cerulean.css" media="screen" title="no title" charset="utf-8">
  <link rel="stylesheet" href="app/assets/stylesheets/styles.css" media="screen" title="no title" charset="utf-8">
</head>
<body>
  <div class="container">

    <%= yield %>

  </div>
</body>
</html>

app/views/photos/new.html.erb
<h1>Add a photo</h1>

<%= form_for current_user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :file %>
  <%= submit_tag "Upload", photos_path, :class => "btn btn-primary" %>
<% end %>

app/views/photos/show.html.erb
<span class="success"><%= flash[:notice] %></span>
<span class="fail"><%= flash[:alert] %></span>

<h1>Your Photos</h1>

<%= image_tag current_user.photos.first.file.url %>
<%= image_tag current_user.photos.first.file.url(:medium) %>
<%= image_tag current_user.photos.first.file.url(:thumb) %>

app/views/users/edit.html.erb
<h4> Welcome <%= current_user.email %> to the edit page</h4>

app/views/users/new.html.erb
<h1>Sign in</h1>

<%= form_for User.new do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<span class="success"><%= flash[:notice] %></span>
<span class="fail"><%= flash[:alert] %></span>

<h1>Hello person with the email of: <%= current_user.email %></h1>

<% if current_user.photos.any? %>

  <%= image_tag current_user.photos.first.file.url %>
  <%= image_tag current_user.photos.first.file.url(:medium) %>
  <%= image_tag current_user.photos.first.file.url(:thumb) %>

<% else %>
  <%= link_to "Add a photo", new_photo_path, :class => "btn btn-primary" %>
<% end %>